### ISSUE TITLE
Correctly import scss from node modules

### ISSUE THREAD

**Issue by larsvanpoucke** [a-ui/acpaas_branding_scss#10]
When I tried to import the quarks, I got this issue:
```
Module build failed:
@import '@a-ui/core/dist/assets/styles/quarks/quarks.mixins';
^
File to import not found or unreadable: @a-ui/core/dist/assets/styles/quarks/quarks.mixins
```

The reason for this issue is because there is missing a `~` before every import from the node_modules in the acpaas branding package.

Reference: https://github.com/gdi2290/angular-starter/issues/727

I fixed these right here: https://github.com/a-ui/acpaas_branding_scss/pull/9

**Comment by TriangleJuice** [comment]
As we discussed mutually, it would be better to use the following code:

```
sassLoader: {
	includePaths: [
		'node_modules'
	]
},
```
or
```
// Webpack 4
{
	loader: 'sass-loader',
	options: {
		"includePaths": [
			require('path').resolve(__dirname, 'node_modules')
		]
	}
}
```

If you still want to go with your first solution, please make sure that our build succeeds and that all necessary tooling (e.g. linters) also work as expected.
