### ISSUE TITLE
Npm install not working, package unreachable

### ISSUE THREAD

**Issue by Secmotic** [a-ui/acpaas_branding_scss#2]
Hi,

Executing NPM install returns an ENOTFOUND error at nexusrepo.antwerpen.be 
`npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo`

**Comment by TriangleJuice** [comment]
The `npm install` is failing for you, because it is requesting a package that's on our private company server. Do you need further assistance?

**Comment by Secmotic** [comment]
Sorry, I didn't see the notification. No further assistance needed, so I will close the issue
